apiVersion: v1
kind: Service
metadata:
    name: devopslab-service
    labels:
        app: tomcat
    spec:
       selector:
         app: tomcat

       ports:
        - port: 8080
          targetPort: 8080

       type: LoadBalancer
